### ISSUE TITLE
serve_forever is not intended for use inside context manager

### ISSUE THREAD

**Issue by Rosuav** [stephenangelico/BioBox#17]
In WebSocket.py, originally the `async with websockets.serve` block then waited on the stop event. That no longer being present, it should still wait on some other event, not on serve_forever, which is intended to stand alone. Considier either removing the context manager and just using serve_forever, or removing the serve_forever in favour of `await asyncio.Future()`.

Relevant tracker issue (also for related points of reuseaddr/port):

https://github.com/aaugustin/websockets/issues/1197

**Comment by stephenangelico** [comment]
Closed in b814ca2.
