### ISSUE TITLE
WebSocket volume management and Chrome extension

### ISSUE THREAD

**Issue by Rosuav** [stephenangelico/BioBox#3]
Possibility: BioBox operates a socket server. Every connected client shows up as a new instance of a Channel subclass, until that client disconnects.

(TODO: Allow channels to be removed at runtime. Adding will probably work, removing probably not.)

Additional feature: A Chrome extension can, when it detects a tab that plays audio, establish a connection for bidirectional volume management. Might work on a limited subset of web sites only; for instance, mandate that it have precisely one `<video>` element.

**Comment by stephenangelico** [comment]
Implemented, including allowing channels to be removed at any time.
